### PR TITLE
Add Pixi and Mac support, and upgrade to Rerun 0.16

### PR DESCRIPTION
**Pull request by pablovela5620**
Rerun visualization should now work on both Mac OS and Linux (Ubuntu 22.04 was what I tested).
Also added pixi to make it super simple to run, and download the model and sample data.

I had to rename `dataset` to `sr_dataset` for simplerecon, timm includes huggingface `datasets` which would break the demo when using pixi.

### CODE REVIEW

**Comment by abey79** [comment]
@pablovela5620 I've open https://github.com/pablovela5620/simplerecon/pull/1 against your branch as I apparently cannot directly push to it (presumably because you used the `main` branch). Are you ok to merge and update to "==0.16" (not rc) whenever we release (should be today, latest Monday)? Otherwise I can open a new pr with everything and `Co-authored-by` you in there.

**Comment by pablovela5620** [comment]
Sure, merged it in there. I'll update to 0.16 whenever ya'll release!

**Comment by abey79** [comment]
We just released 🚀

**Comment by pablovela5620** [comment]
Done, should be good to merge. Tested on my mac again and it ran fine (though extremely slow 🐢)

**Pull request merged**
